include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - avoid_print
    - sort_pub_dependencies
    - unnecessary_null_checks
    - prefer_final_fields
    - avoid_unused_constructor_parameters
    - avoid_function_literals_in_foreach_calls
    - prefer_collection_literals
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - prefer_single_quotes
    - always_declare_return_types